[package]
name = "hupa"
version = "0.1.0"
authors = ["notkild <notkild@gmail.com>"]

[dependencies]
app_dirs = "1.1"
clap = "2.21"
error-chain = "0.10"
json = { version = "0.11", optional = true }

[features]
default = ["text-json"]
text-json = ["json"]

[[bin]]
name = "hupa"
