[package]
name = "hupa"
version = "0.3.0"
authors = ["notkild <notkild@gmail.com>"]

[dependencies]
app_dirs = "1.1"
clap = "2.23"
colored = "1.4"
humansize = "1.0"

[dependencies.libhupa]
path = "../lib"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
