[package]
name = "hupa"
version = "0.3.2"
authors = ["fourdotfiveg <fourdotfiveg@gmail.com>"]

[dependencies]
clap = "2.23"
colored = "1.4"
humansize = "1.0"

[dependencies.libhupa]
path = "../lib"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
