[package]
name = "hupad"
version = "0.3.1"
authors = ["notkild <notkild@gmail.com>"]

[dependencies]
app_dirs = "1.1"
clap = "2.23"
daemonize = "0.2"
time = "0.1"

[dependencies.libhupa]
path = "../lib"
